# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_pollzouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollzouser',
            name='desciption',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
