# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_pollzouser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollzouser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_pollzouser_following_+', to='userProfile.PollzoUser'),
        ),
    ]
