# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20170429_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollzouser',
            name='desciption',
            field=models.CharField(blank=True, default=b'', max_length=1000),
        ),
    ]
