# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_auto_20170429_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(upload_to=b'cover_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='pollzouser',
            name='cover_photo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='userProfile.CoverPhoto'),
            preserve_default=False,
        ),
    ]
