# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_auto_20170430_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollzouser',
            name='cover_photo',
        ),
        migrations.DeleteModel(
            name='CoverPhoto',
        ),
    ]
