# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollzouser',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.CoverPhoto'),
        ),
    ]
