# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0017_pollzouser_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverphoto',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
