# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0019_auto_20170502_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='interests',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Interest'),
            preserve_default=False,
        ),
    ]
