# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0020_question_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='interests',
        ),
        migrations.AddField(
            model_name='question',
            name='interests',
            field=models.ManyToManyField(to='userProfile.Interest'),
        ),
    ]
